openapi: 3.0.0
info:
  title: ODC TODO API
  description: A Todo API for ODC Test
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /tasks:
    get:
      summary: Search Tasks
      parameters:
        - name: name
          in: query
          description: Task name
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: Task status
          required: false
          schema:
            type: string
            enum: [TODO, IN_PROGRESS, COMPLETED]
            example: TODO
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      requestBody:
        description: Task to create, 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{id}:
    get:
      summary: Get a task by id
      parameters:
        - name: id
          in: path
          description: Task id
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Got the task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    patch:
      summary: Partialy update a task by id
      parameters:
        - name: id
          in: path
          description: Task id
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        description: Task to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '204':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    delete:
      summary: Delete a task by id
      parameters:
        - name: id
          in: path
          description: Task id
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '204':
          description: Deleted
        '404':
          description: Task not found
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
          readOnly: true
        name:
          type: string
          example: Buy Milk
        startDate:
          type: string
          format: date
          example: 2021-01-01
        endDate:
          type: string
          format: date
          example: 2021-01-02
        status:
          type: string
          enum: [TODO, IN_PROGRESS, COMPLETED]
          example: TODO
      required:
        - name